TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 1.2
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  #I believe this parameter determines whether the robot can move side to side. 
  holonomic_robot: false